services:
  - type: web
    name: mami-supermarket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    plan: free 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mami-supermarket-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /api/v1/health
    autoDeploy: true
    buildFilter:
      paths: ["mami-supermarket-backend/**"]
    repo: https://github.com/matanmalka1/mami-supermarket-backend.git

  - type: web 
    name: mami-supermarket-frontend
    env: static 
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    
    envVars:
      - key: VITE_API_BASE_URL
        value: https://mami-supermarket-backend.onrender.com/api/v1
    
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths: ["mami-supermarket-frontend/**"]
    repo: https://github.com/matanmalka1/mami-supermarket-frontend.git

databases:
  - name: mami-supermarket-db
    plan: free